# -*- coding: utf-8 -*-
#RobL-v-v-v-v-v-v-v-v-v-v-#-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-v-
#
# podcastmetadata.py
# ------------------
# This is a new module added for the gPodder+ project. This module is self-
# contained so the code can live outside of the existing gPodder source files.
# The entirety of this module was added by RobL and all of the code with a few
# minor exceptions was generated by ChatGPT.
#
# This module adds the ability to lookup podcast metadata from external sources,
# such as PodcastIndex.org amd Apple iTunes, to populate podcast and episode
# metadata within the gPodder database. It is designed to be used as a separate
# metadata service that can be called from the gPodder UI when the user wants
# to improve episode descriptions from the RSS feed. It is not integrated into
# the normal feed parsing and subscription update flow.
#-------------------------------------------------------------------------------
# gPodder+ - An augmentation to and modification of the gPodder codebase
# Copyright (c) 2026 Rob L.
#
# gPodder+ is free software that applies the same GNU licensing and statements
# of non-warranty as the original gPodder codebase. It is a derivative work
# that builds on the original gPodder code, which is licensed under the GNU
# General Public License v3.0 or later. gPodder+ is not a separate software
# project and does not have its own license.#
#-------------------------------------------------------------------------------
# gPodder - A media aggregator and podcast client
# Copyright (c) 2005-2026 The gPodder Team
#
# gPodder is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# gPodder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#RobL-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-
#
import abc
import hashlib
import logging
import time
import urllib.parse
from io import BytesIO

import podcastparser

import gpodder
from gpodder import util

# Text string processor for internationalization/localization.
_ = gpodder.gettext

# Plural-aware text string processor (1 egg, 2 eggs)
N_ = gpodder.ngettext

# Set up module-level logger.
logger = logging.getLogger(__name__)
#logger.setLevel(logging.INFO)

#===============================================================================
# Module-level Helper Functions
#===============================================================================
def create_metadata_service(config, include_rss=True):
    """Create the configured podcast metadata service."""

    providers = []

    if include_rss:
        logger.info('Adding RSS metadata provider')
        providers.append(RSSFeedMetadataProvider())

    try:
        enabled = config.metadata.podcast_index.enabled
        api_key = config.metadata.podcast_index.api_key
        api_secret = config.metadata.podcast_index.api_secret

        logger.info(
            'Podcast Index config info: '
            'enabled=%s, api_key_present=%s, api_secret_present=%s',
            enabled,
            bool(api_key),
            bool(api_secret),
        )

        if enabled and api_key and api_secret:
            providers.append(PodcastIndexMetadataProvider(
                api_key=api_key,
                api_secret=api_secret,
                user_agent='gPodder+/1.0',
            ))
            logger.info('Adding Podcast Index metadata provider')
        else:
            logger.warning(
                'Skipping Podcast Index due to missing config info: '
                'enabled=%s, api_key_present=%s, api_secret_present=%s',
                enabled,
                bool(api_key),
                bool(api_secret),
            )

    except AttributeError:
        logger.warning('Podcast Index metadata config is missing', exc_info=True)

    try:
        enabled = config.metadata.apple_itunes.enabled
        logger.info('Apple iTunes metadata config: enabled=%s', enabled)

        if enabled:
            providers.append(AppleITunesSearchMetadataProvider())
            logger.info('Adding Apple iTunes metadata provider')
        else:
            logger.warning('Skipping Apple iTunes metadata provider because it is disabled')

    except AttributeError:
        logger.warning('Apple iTunes metadata config is missing; enabling Apple fallback', exc_info=True)
        providers.append(AppleITunesSearchMetadataProvider())

    logger.info(
        'Active metadata providers: %s',
        ', '.join(provider.name for provider in providers) or '(none)'
    )

    return PodcastMetadataService(providers)

#===============================================================================
class PodcastMetadataError(Exception):
    pass

#===============================================================================
class PodcastMetadataNotConfigured(PodcastMetadataError):
    pass

#===============================================================================
class MetadataPodcast(object):
    def __init__(
            self,
            title=None,
            feed_url=None,
            website_url=None,
            description=None,
            image_url=None,
            author=None,
            language=None,
            categories=None,
            source=None,
            source_id=None,
            raw=None):
        self.title = title
        self.feed_url = feed_url
        self.website_url = website_url
        self.description = description
        self.image_url = image_url
        self.author = author
        self.language = language
        self.categories = categories or []
        self.source = source
        self.source_id = source_id
        self.raw = raw or {}

#===============================================================================
class MetadataEpisode(object):
    def __init__(
            self,
            title=None,
            url=None,
            link=None,
            description=None,
            published=None,
            duration=None,
            image_url=None,
            season=None,
            number=None,
            guid=None,
            source=None,
            source_id=None,
            raw=None):
        self.title = title
        self.url = url
        self.link = link
        self.description = description
        self.published = published
        self.duration = duration
        self.image_url = image_url
        self.season = season
        self.number = number
        self.guid = guid
        self.source = source
        self.source_id = source_id
        self.raw = raw or {}

#===============================================================================
class PodcastMetadataProvider(object, metaclass=abc.ABCMeta):
    name = 'metadata-provider'

    def get_episodes(self, podcast, limit=25):
        raise NotImplementedError()

    def is_configured(self):
        return True

    def lookup_by_feed_url(self, feed_url):
        raise NotImplementedError()

    def search_podcasts(self, query, limit=25):
        raise NotImplementedError()

#===============================================================================
class RSSFeedMetadataProvider(PodcastMetadataProvider):
    """
    Uses the podcast's own RSS/Atom feed.

    This is the authoritative source for subscribed podcasts and should remain
    the default source for normal gPodder updates.
    """

    name = 'rss'

    #---------------------------------------------------------------------------
    # Public Methods
    #---------------------------------------------------------------------------
    def get_episodes(self, podcast, limit=25):
        feed_url = podcast.feed_url if isinstance(podcast, MetadataPodcast) else podcast
        feed = self._parse_feed_url(feed_url)

        episodes = []
        for item in feed.get('episodes', [])[:limit]:
            episodes.append(MetadataEpisode(
                title=item.get('title'),
                url=item.get('url'),
                link=item.get('link'),
                description=item.get('description'),
                published=item.get('published'),
                duration=item.get('total_time'),
                image_url=item.get('episode_art_url'),
                season=item.get('season'),
                number=item.get('number'),
                guid=item.get('guid'),
                source=self.name,
                source_id=item.get('guid') or item.get('url'),
                raw=item,
            ))

        return episodes

    def lookup_by_feed_url(self, feed_url):
        feed = self._parse_feed_url(feed_url)

        return MetadataPodcast(
            title=feed.get('title'),
            feed_url=feed_url,
            website_url=feed.get('link'),
            description=feed.get('description'),
            image_url=feed.get('cover_url'),
            author=feed.get('author') or feed.get('itunes_author'),
            language=feed.get('language'),
            categories=feed.get('categories') or [],
            source=self.name,
            source_id=feed_url,
            raw=feed,
        )

    def search_podcasts(self, query, limit=25):
        # RSS itself cannot search the web.
        return []

    #---------------------------------------------------------------------------
    # Private Methods
    #---------------------------------------------------------------------------
    def _parse_feed_url(self, feed_url):
        response = util.urlopen(feed_url)

        if not response.ok:
            raise PodcastMetadataError(
                'Could not fetch feed: %s: %d %s' %
                (feed_url, response.status_code, response.reason)
            )

        feed = podcastparser.parse(feed_url, BytesIO(response.content))
        feed['url'] = feed_url
        return feed

#===============================================================================
class PodcastIndexMetadataProvider(PodcastMetadataProvider):
    """
    Podcast Index provider.

    Requires:
        podcast_index.api_key
        podcast_index.api_secret

    Do not hard-code credentials in source.
    """

    name = 'podcastindex'
    BASE_URL = 'https://api.podcastindex.org/api/1.0'

    def __init__(self, api_key=None, api_secret=None, user_agent=None):
        self.api_key = api_key
        self.api_secret = api_secret
        self.user_agent = user_agent or 'gPodder+/1.0'

    #---------------------------------------------------------------------------
    # Public Methods
    #---------------------------------------------------------------------------
    def get_episodes(self, podcast, limit=25):
        if not isinstance(podcast, MetadataPodcast):
            raise PodcastMetadataError('Podcast Index episodes require a MetadataPodcast')

        if podcast.source_id is None:
            # Fall back to lookup by feed URL.
            podcast = self.lookup_by_feed_url(podcast.feed_url)

        if podcast is None or podcast.source_id is None:
            return []

        data = self._get_json('/episodes/byfeedid', {
            'id': podcast.source_id,
            'max': limit,
        })

        return [
            self._episode_from_item(item)
            for item in data.get('items', [])
        ]

    def is_configured(self):
        return bool(self.api_key and self.api_secret)

    def lookup_by_feed_url(self, feed_url):
        data = self._get_json('/podcasts/byfeedurl', {
            'url': feed_url,
        })

        feed = data.get('feed')
        if not feed:
            return None

        return self._podcast_from_feed(feed)

    def search_podcasts(self, query, limit=25):
        data = self._get_json('/search/byterm', {
            'q': query,
            'max': limit,
        })

        return [
            self._podcast_from_feed(feed)
            for feed in data.get('feeds', [])
        ]

    #---------------------------------------------------------------------------
    # Private Methods
    #---------------------------------------------------------------------------
    def _episode_from_item(self, item):
        return MetadataEpisode(
            title=item.get('title'),
            url=item.get('enclosureUrl'),
            link=item.get('link'),
            description=item.get('description'),
            published=item.get('datePublished') or item.get('datePublishedPretty'),
            duration=item.get('duration'),
            image_url=item.get('image') or item.get('feedImage'),
            season=item.get('season'),
            number=item.get('episode'),
            guid=item.get('guid'),
            source=self.name,
            source_id=item.get('id'),
            raw=item,
        )

    def _get_json(self, path, params=None):
        params = params or {}
        query = urllib.parse.urlencode(params)
        url = self.BASE_URL + path
        if query:
            url += '?' + query

        response = util.urlopen(url, headers=self._headers())

        if not response.ok:
            raise PodcastMetadataError(
                'Podcast Index request failed: %s: %d %s' %
                (url, response.status_code, response.reason)
            )

        return response.json()

    def _headers(self):
        if not self.is_configured():
            raise PodcastMetadataNotConfigured(
                'Podcast Index API key/secret are not configured'
            )

        auth_date = str(int(time.time()))
        auth_hash = hashlib.sha1(
            (self.api_key + self.api_secret + auth_date).encode('utf-8')
        ).hexdigest()

        return {
            'User-Agent': self.user_agent,
            'X-Auth-Key': self.api_key,
            'X-Auth-Date': auth_date,
            'Authorization': auth_hash,
        }

    def _podcast_from_feed(self, feed):
        categories = feed.get('categories') or {}
        if isinstance(categories, dict):
            categories = list(categories.values())

        return MetadataPodcast(
            title=feed.get('title'),
            feed_url=feed.get('url') or feed.get('originalUrl'),
            website_url=feed.get('link'),
            description=feed.get('description'),
            image_url=feed.get('image') or feed.get('artwork'),
            author=feed.get('author') or feed.get('ownerName'),
            language=feed.get('language'),
            categories=categories,
            source=self.name,
            source_id=feed.get('id'),
            raw=feed,
        )

#===============================================================================
class AppleITunesSearchMetadataProvider(PodcastMetadataProvider):
    """
    Apple iTunes Search provider.

    Useful as a fallback discovery provider. Do not treat it as the primary
    metadata authority for subscribed podcasts.
    """

    name = 'apple-itunes'
    SEARCH_URL = 'https://itunes.apple.com/search'
    LOOKUP_URL = 'https://itunes.apple.com/lookup'

    #---------------------------------------------------------------------------
    # Public Methods
    #---------------------------------------------------------------------------
    def get_episodes(self, podcast, limit=25):
        if not isinstance(podcast, MetadataPodcast) or podcast.source_id is None:
            return []

        data = self._get_json(self.LOOKUP_URL, {
            'id': podcast.source_id,
            'media': 'podcast',
            'entity': 'podcastEpisode',
            'limit': limit,
        })

        episodes = []

        for item in data.get('results', []):
            if item.get('wrapperType') == 'collection':
                continue

            if (item.get('kind') == 'podcast-episode' or
                item.get('wrapperType') == 'track' or
                item.get('episodeUrl') or
                item.get('trackName')):
                episodes.append(self._episode_from_result(item))

        logger.info(
            'Apple lookup returned result types: %s',
            [
                {
                    'wrapperType': item.get('wrapperType'),
                    'kind': item.get('kind'),
                    'trackName': item.get('trackName'),
                }
                for item in data.get('results', [])[:10]
            ],
        )

        return episodes

    def lookup_by_feed_url(self, feed_url):
        # Apple has no reliable direct lookup-by-feed-url endpoint.
        # Search by URL as a fallback, then match exact feedUrl when present.
        results = self.search_podcasts(feed_url, limit=25)

        for podcast in results:
            if podcast.feed_url == feed_url:
                return podcast

        return None

    def search_podcasts(self, query, limit=25):
        data = self._get_json(self.SEARCH_URL, {
            'term': query,
            'media': 'podcast',
            'entity': 'podcast',
            'limit': limit,
        })

        return [
            self._podcast_from_result(item)
            for item in data.get('results', [])
        ]

    #---------------------------------------------------------------------------
    # Private Methods
    #---------------------------------------------------------------------------
    def _episode_from_result(self, result):
        return MetadataEpisode(
            title=result.get('trackName'),
            url=result.get('episodeUrl') or result.get('previewUrl'),
            link=result.get('trackViewUrl'),
            description=result.get('description'),
            published=result.get('releaseDate'),
            duration=result.get('trackTimeMillis'),
            image_url=(
                result.get('artworkUrl600') or
                result.get('artworkUrl100') or
                result.get('artworkUrl60')
            ),
            season=result.get('seasonNumber'),
            number=result.get('episodeNumber'),
            guid=None,
            source=self.name,
            source_id=result.get('trackId'),
            raw=result,
        )

    def _get_json(self, base_url, params):
        url = base_url + '?' + urllib.parse.urlencode(params)
        response = util.urlopen(url)

        if not response.ok:
            raise PodcastMetadataError(
                'Apple iTunes request failed: %s: %d %s' %
                (url, response.status_code, response.reason)
            )

        return response.json()

    def _podcast_from_result(self, result):
        return MetadataPodcast(
            title=result.get('collectionName') or result.get('trackName'),
            feed_url=result.get('feedUrl'),
            website_url=result.get('collectionViewUrl') or result.get('trackViewUrl'),
            description=result.get('description'),
            image_url=(
                result.get('artworkUrl600') or
                result.get('artworkUrl100') or
                result.get('artworkUrl60')
            ),
            author=result.get('artistName'),
            language=None,
            categories=[result.get('primaryGenreName')] if result.get('primaryGenreName') else [],
            source=self.name,
            source_id=result.get('collectionId') or result.get('trackId'),
            raw=result,
        )

#===============================================================================
class PodcastMetadataService(object):
    """
    Ordered metadata service.

    Suggested order:
        1. RSS
        2. Podcast Index
        3. Apple iTunes Search
    """

    def __init__(self, providers=None):
        self.providers = providers or []

    #---------------------------------------------------------------------------
    # Public Methods
    #---------------------------------------------------------------------------
    def get_episodes(self, podcast, limit=25):
        for provider in self.providers:
            if not provider.is_configured():
                continue

            try:
                episodes = provider.get_episodes(podcast, limit)
                if episodes:
                    return episodes
            except Exception:
                logger.warning('Metadata provider failed: %s', provider.name, exc_info=True)

        return []

    def get_episodes_from_all_providers(self, podcast, limit=25):
        """Return episode metadata from all configured non-RSS providers.

        Each provider resolves the podcast independently so provider-specific IDs
        are correct. This is required because Podcast Index feed IDs and Apple
        collection IDs are not interchangeable.
        """

        results = []

        feed_url = getattr(podcast, 'feed_url', None) or getattr(podcast, 'url', None)
        title = getattr(podcast, 'title', None)

        logger.info(
            'Getting episodes from all providers: title=%r feed_url=%r',
            title,
            feed_url,
        )

        for provider in self.providers:
            if not provider.is_configured():
                logger.info('Skipping unconfigured episode provider: %s', provider.name)
                continue

            # RSS is handled separately by apply_rss_description_fallback().
            if provider.name == 'rss':
                logger.info('Skipping RSS since it is handled separately by apply_rss_description_fallback()')
                continue

            try:
                provider_podcast = self._resolve_podcast_for_provider(
                    provider,
                    title=title,
                    feed_url=feed_url,
                )

                if provider_podcast is None:
                    logger.info(
                        'Episode provider %s could not resolve podcast: title=%r feed_url=%r',
                        provider.name,
                        title,
                        feed_url,
                    )
                    continue

                logger.info(
                    'Episode provider %s resolved podcast: title=%r feed_url=%r source_id=%r',
                    provider.name,
                    getattr(provider_podcast, 'title', None),
                    getattr(provider_podcast, 'feed_url', None),
                    getattr(provider_podcast, 'source_id', None),
                )

                episodes = provider.get_episodes(provider_podcast, limit=limit)

                logger.info(
                    'Episode provider %s returned %d episode(s)',
                    provider.name,
                    len(episodes),
                )

                results.extend(episodes)

            except Exception:
                logger.warning(
                    'Episode provider failed: %s',
                    provider.name,
                    exc_info=True,
                )

        results = self._dedupe_episodes_by_source(results)

        source_counts = {}
        for episode in results:
            source = getattr(episode, 'source', None) or '(unknown)'
            source_counts[source] = source_counts.get(source, 0) + 1

        logger.info(
            'All-provider episode search returned %d result(s) by source: %s',
            len(results),
            source_counts,
        )

        return results

    def get_episodes_with_rss_description_fallback(self, podcast, limit=25):
        """Return episodes using normal provider order, then improve weak
        descriptions from the podcast RSS feed when possible.

        This preserves the existing first-provider-wins behavior.
        """

        episodes = self.get_episodes(podcast, limit=limit)

        return self.rss_description_fallback(
            podcast,
            episodes,
            limit=limit,
        )

    def lookup_by_feed_url(self, feed_url):
        for provider in self.providers:
            if not provider.is_configured():
                continue

            try:
                result = provider.lookup_by_feed_url(feed_url)
                if result is not None:
                    return result
            except Exception:
                logger.warning('Metadata provider failed: %s', provider.name, exc_info=True)

        return None

    def rss_description_fallback(self, podcast, episodes, limit=25):
        """Fill short/truncated episode descriptions from the podcast RSS feed.

        This does not decide where the episode list comes from. It only improves
        the descriptions of the episode objects passed in.
        """

        if not episodes:
            return []

        feed_url = getattr(podcast, 'feed_url', None)
        if not feed_url:
            logger.info(
                'RSS description fallback skipped because podcast has no feed_url: %r',
                getattr(podcast, 'title', None),
            )
            return episodes

        try:
            rss_provider = RSSFeedMetadataProvider()
            rss_episodes = rss_provider.get_episodes(feed_url, limit=max(limit, 200))
        except Exception:
            logger.warning(
                'RSS description fallback failed for feed_url=%s',
                feed_url,
                exc_info=True,
            )
            return episodes

        if not rss_episodes:
            logger.info(
                'RSS description fallback found no RSS episodes for feed_url=%s',
                feed_url,
            )
            return episodes

        rss_index = self._build_episode_match_index(rss_episodes)

        updated_count = 0

        for episode in episodes:
            rss_episode = self._find_matching_episode(episode, rss_index)

            if rss_episode is None:
                continue

            if self._should_replace_description(
                    getattr(episode, 'description', None),
                    getattr(rss_episode, 'description', None)):
                episode.description = rss_episode.description
                updated_count += 1

                try:
                    episode.raw['description_source'] = 'rss-fallback'
                except Exception:
                    pass

                logger.info(
                    'Replaced short metadata description from RSS: title=%r source=%s rss_desc_len=%d',
                    getattr(episode, 'title', None),
                    getattr(episode, 'source', None),
                    len(rss_episode.description or ''),
                )

        logger.info(
            'RSS description fallback updated %d of %d episode description(s)',
            updated_count,
            len(episodes),
        )

        return episodes

    def search_podcasts(self, query, limit=25):
        results = []

        for provider in self.providers:
            if not provider.is_configured():
                logger.warning(
                    'Skipping metadata provider %s because it is not configured',
                    provider.name,
                )
                continue

            try:
                logger.info('Searching metadata provider %s for query: %s', provider.name, query)
                provider_results = provider.search_podcasts(query, limit)
                logger.info(
                    'Metadata provider %s returned %d result(s)',
                    provider.name,
                    len(provider_results),
                )
                results.extend(provider_results)

            except Exception:
                logger.warning(
                    'Metadata provider failed: %s',
                    provider.name,
                    exc_info=True,
                )

        results = self._dedupe_podcasts(results)

        logger.info(
            'Combined metadata search returned %d deduped result(s)',
            len(results),
        )

        return results[:limit]

    def search_podcasts_from_all_providers(self, query, limit_per_provider=25,
                                           dedupe_across_sources=False):
        """Search all configured podcast metadata providers.

        Unlike search_podcasts(), this is intended for UI result selection.
        It preserves provider/source visibility so the user can see whether a
        result came from Podcast Index, Apple iTunes, or another provider.
        """

        results = []

        for provider in self.providers:
            if not provider.is_configured():
                logger.warning(
                    'Skipping metadata provider %s because it is not configured',
                    provider.name,
                )
                continue

            try:
                logger.info(
                    'Searching metadata provider %s for query: %s',
                    provider.name,
                    query,
                )

                provider_results = provider.search_podcasts(
                    query,
                    limit=limit_per_provider,
                )

                logger.info(
                    'Metadata provider %s returned %d podcast result(s)',
                    provider.name,
                    len(provider_results),
                )

                results.extend(provider_results)

            except Exception:
                logger.warning(
                    'Metadata provider failed during all-provider podcast search: %s',
                    provider.name,
                    exc_info=True,
                )

        if dedupe_across_sources:
            results = self._dedupe_podcasts(results)
        else:
            results = self._dedupe_podcasts_by_source(results)

        source_counts = {}
        for podcast in results:
            source = getattr(podcast, 'source', None) or '(unknown)'
            source_counts[source] = source_counts.get(source, 0) + 1

        logger.info(
            'All-provider podcast search returned %d result(s) by source: %s',
            len(results),
            source_counts,
        )

        return results

    #---------------------------------------------------------------------------
    # Private Methods
    #---------------------------------------------------------------------------
    def _best_podcast_match(self, matches, title=None, feed_url=None):
        if not matches:
            return None

        norm_feed_url = self._norm_key(feed_url)
        norm_title = self._norm_title(title)

        if norm_feed_url:
            for match in matches:
                if self._norm_key(getattr(match, 'feed_url', None)) == norm_feed_url:
                    return match

        if norm_title:
            for match in matches:
                if self._norm_title(getattr(match, 'title', None)) == norm_title:
                    return match

        return matches[0]

    def _build_episode_match_index(self, episodes):
        index = {
            'guid': {},
            'url': {},
            'link': {},
            'title_published': {},
            'title': {},
        }

        for episode in episodes:
            guid = self._norm_key(getattr(episode, 'guid', None))
            url = self._norm_key(getattr(episode, 'url', None))
            link = self._norm_key(getattr(episode, 'link', None))
            title = self._norm_title(getattr(episode, 'title', None))
            published_key = self._published_key(getattr(episode, 'published', None))

            if guid:
                index['guid'][guid] = episode

            if url:
                index['url'][url] = episode

            if link:
                index['link'][link] = episode

            if title and published_key:
                index['title_published'][(title, published_key)] = episode

            if title:
                index['title'].setdefault(title, episode)

        return index

    def _dedupe_episodes(self, episodes):
        """Remove duplicate episodes results across all providers/sources
           based on guid, url, link, or title+published date."""

        result = []
        seen = set()

        for episode in episodes:
            key = (
                self._norm_key(getattr(episode, 'guid', None)) or
                self._norm_key(getattr(episode, 'url', None)) or
                self._norm_key(getattr(episode, 'link', None))
            )

            if not key:
                title = self._norm_title(getattr(episode, 'title', None))
                published = self._published_key(getattr(episode, 'published', None))
                key = '%s|%s' % (title, published)

            if not key or key in seen:
                continue

            seen.add(key)
            result.append(episode)

        return result

    def _dedupe_episodes_by_source(self, episodes):
        """Remove duplicate episode results only within the same provider/source
           to preserve visibility of duplicates across sources."""

        result = []
        seen = set()

        for episode in episodes:
            source = getattr(episode, 'source', None) or ''

            key = (
                self._norm_key(getattr(episode, 'guid', None)) or
                self._norm_key(getattr(episode, 'url', None)) or
                self._norm_key(getattr(episode, 'link', None))
            )

            if not key:
                title = self._norm_title(getattr(episode, 'title', None))
                published = self._published_key(getattr(episode, 'published', None))
                key = '%s|%s' % (title, published)

            if not key:
                continue

            dedupe_key = '%s|%s' % (source.strip().lower(), key)

            if dedupe_key in seen:
                continue

            seen.add(dedupe_key)
            result.append(episode)

        return result

    def _dedupe_podcasts(self, podcasts):
        """Remove duplicate podcast results across all providers/sources
           based on feed URL, website URL, or title."""
        result = []
        seen = set()

        for podcast in podcasts:
            key = podcast.feed_url or podcast.website_url or podcast.title
            if not key:
                continue

            key = key.strip().lower()
            if key in seen:
                continue

            seen.add(key)
            result.append(podcast)

        return result

    def _dedupe_podcasts_by_source(self, podcasts):
        """Remove duplicate podcast results only within the same provider/source.

        This preserves source visibility in UI search results. For example, the
        same podcast returned by Podcast Index and Apple iTunes will appear twice,
        once for each source, but duplicate Apple results are collapsed.
        """

        result = []
        seen = set()

        for podcast in podcasts:
            source = getattr(podcast, 'source', None) or ''

            key = (
                getattr(podcast, 'feed_url', None) or
                getattr(podcast, 'website_url', None) or
                getattr(podcast, 'title', None)
            )

            if not key:
                continue

            dedupe_key = '%s|%s' % (
                source.strip().lower(),
                key.strip().lower(),
            )

            if dedupe_key in seen:
                continue

            seen.add(dedupe_key)
            result.append(podcast)

        return result

    def _find_matching_episode(self, episode, rss_index):
        guid = self._norm_key(getattr(episode, 'guid', None))
        url = self._norm_key(getattr(episode, 'url', None))
        link = self._norm_key(getattr(episode, 'link', None))
        title = self._norm_title(getattr(episode, 'title', None))
        published_key = self._published_key(getattr(episode, 'published', None))

        if guid and guid in rss_index['guid']:
            return rss_index['guid'][guid]

        if url and url in rss_index['url']:
            return rss_index['url'][url]

        if link and link in rss_index['link']:
            return rss_index['link'][link]

        if title and published_key:
            match = rss_index['title_published'].get((title, published_key))
            if match is not None:
                return match

        if title:
            return rss_index['title'].get(title)

        return None

    def _norm_key(self, value):
        value = (value or '').strip()
        return value.lower() if value else ''

    def _norm_title(self, value):
        value = (value or '').strip().lower()
        if not value:
            return ''

        return ' '.join(value.split())

    def _published_key(self, value):
        if value is None:
            return ''

        try:
            if isinstance(value, int):
                return time.strftime('%Y-%m-%d', time.localtime(value))

            value = str(value).strip()
            if len(value) >= 10:
                return value[:10]

        except Exception:
            logger.debug('Could not normalize published date: %r', value, exc_info=True)

        return ''

    def _resolve_podcast_for_provider(self, provider, title=None, feed_url=None):
        """Resolve a podcast using the provider's own lookup/search methods."""

        provider_podcast = None

        if feed_url:
            try:
                provider_podcast = provider.lookup_by_feed_url(feed_url)
            except Exception:
                logger.warning(
                    'Provider %s lookup_by_feed_url failed for %r',
                    provider.name,
                    feed_url,
                    exc_info=True,
                )

        if provider_podcast is not None:
            return provider_podcast

        if title:
            try:
                matches = provider.search_podcasts(title, limit=10)
            except Exception:
                logger.warning(
                    'Provider %s search_podcasts failed for %r',
                    provider.name,
                    title,
                    exc_info=True,
                )
                return None

            return self._best_podcast_match(
                matches,
                title=title,
                feed_url=feed_url,
            )

        return None

    def _should_replace_description(self, current_description, rss_description):
        current = (current_description or '').strip()
        rss = (rss_description or '').strip()

        if not rss:
            return False

        if not current:
            return True

        current_looks_truncated = (
            current.endswith('...') or
            current.endswith('…')
        )

        if current_looks_truncated and len(rss) > len(current):
            return True

        if len(rss) >= max(len(current) * 2, len(current) + 300):
            return True

        return False
